#jpa
spring:
  jpa: 
    show-sql: true
    generate-ddl: false
    database: MYSQL
    hibernate: 
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/taste?characterEncoding=UTF-8
    username:  root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  # 静态资源
  mvc: 
    view:
      prefix: /jsp/ 
      suffix:  .jsp